baseURL = 'https://fishcrap.github.io/blog/'
languageCode = 'en-us'
# languageCode = 'en'
title = "Xujie's Blog"
theme = "hugo-coder"


paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"


[params]
  author = "Xujie Shen"
  info = "Student of Zhejiang University"
  description = "Xujie's personal blog"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"

  favicon_32 = "images/favicon-32x32.png"
  favicon_16 = "images/favicon-16x16.png"
  touchIcon = "images/apple-touch-icon.png"

  since = 2021

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

#   customCSS = ["css/custom.css"]
#   customSCSS = ["scss/custom.scss"]
#   customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/fishcrap/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
